apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.branchName }}
  namespace: {{ .Values.branchName }}
  labels:
    app: {{ .Values.branchName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.branchName }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.branchName }}
    spec:
      containers:
        - name: {{ .Values.branchName }}
          image: "registry.git.geogebra.org/solver-team/solver-engine/api:{{ .Values.branchName }}"
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/{{ .Values.branchName }}"
          # resources:
          #   limits:
          #     memory: "100Mi"
          #     cpu: "200m"
      imagePullSecrets:
        - name: ggb-registry-key