apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.branchName }}
  namespace: "solver-{{ .Values.branchName }}"
  labels:
    app: {{ .Values.branchName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.branchName }}
  replicas: 1
  template:
    metadata:
      annotations:
        # This annotation is necessary to update the deployed pod for a branch as the image name doesn't change
        solver/commit-sha: {{ .Values.commitSha }}
      labels:
        app: {{ .Values.branchName }}
    spec:
      containers:
        - name: {{ .Values.branchName }}
          image: "registry.git.geogebra.org/solver-team/solver-engine/api:{{ .Values.branchName }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/{{ .Values.branchName }}"
            - name: SOLVER_COMMIT_SHA
              value: "{{ .Values.commitSha }}"
            - name: DEPLOYMENT_NAME
              value: "{{ .Values.branchName }}"
      imagePullSecrets:
        - name: ggb-registry-key