apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace: "solver-{{ .Values.deploymentName }}"
  labels:
    app: {{ .Values.deploymentName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deploymentName }}
  replicas: {{ .Values.minReplicas }}
  template:
    metadata:
      annotations:
        # This annotation is necessary to update the deployed pod for a branch as the image name doesn't change
        solver/commit-sha: {{ .Values.commitSha }}
      labels:
        app: {{ .Values.deploymentName }}
    spec:
      containers:
        - name: {{ .Values.deploymentName }}
          image: "registry.git.geogebra.org/solver-team/solver-engine/api:{{ .Values.solverImageTag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "{{ .Values.contextPath }}"
            - name: SOLVER_COMMIT_SHA
              value: "{{ .Values.commitSha }}"
            - name: DEPLOYMENT_NAME
              value: "{{ .Values.deploymentName }}"
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.springProfile }}"
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: "{{ .Values.contextPath }}/actuator/health/liveness"
              port: 8080
              initialDelaySeconds: 15
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 1
          {{ if eq .Values.deploymentDomain "solver-api.geogebra.org" }}
          resources:
            requests:
              cpu: {{ .Values.cpuSoftLimit }}
            limits:
              memory: {{ .Values.memoryHardLimit }}
          {{ end }}
      imagePullSecrets:
        - name: ggb-registry-key