{{ if eq .Values.deploymentDomain "solver-api.geogebra.org" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "solver-{{ .Values.deploymentName }}-hpa"
  namespace: "solver-{{ .Values.deploymentName }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.deploymentName }}
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
{{ end }}