apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "solver-{{ .Values.deploymentName }}-hpa"
  namespace: "solver-{{ .Values.deploymentName }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.deploymentName }}
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50