apiVersion: v1
kind: Secret
metadata:
  name: ggb-registry-key
  namespace: 'solver-{{ .Values.deploymentName }}'
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
