{{- if .Values.imageCredentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: ggb-registry-key
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}