apiVersion: v1
kind: Service
metadata:
  namespace: "solver-{{ .Values.deploymentName }}"
  name: {{ .Values.deploymentName }}-service
  labels:
    app: {{ .Values.deploymentName }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/{{ .Values.contextPath }}/poker.html"
spec:
  type: NodePort
  selector:
    app: {{ .Values.deploymentName }}
  ports:
    - port: 80
      targetPort: 8080
