apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.branchName }}
  name: {{ .Values.branchName }}-service
  labels:
    app: {{ .Values.branchName }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/{{ .Values.branchName }}/poker.html"
spec:
  type: NodePort
  selector:
    app: {{ .Values.branchName }}
  ports:
    - port: 80
      targetPort: 8080
