openapi: 3.0.3

info:
  title: 'GeoGebra Solver API'
  version: '1.0'
servers:
  - url: http://localhost:8080/api/v1/

paths:
  /versionInfo:
    get:
      operationId: getVersionInfo
      description: 'Get solver version info'
      responses:
        '200':
          description: 'Successfully returned version info'
          content:
            application/json:
              schema:
                $ref: 'VersionInfo.yaml'

  /plans:
    get:
      operationId: listPlans
      description: 'List all available plan IDs'
      responses:
        '200':
          description: 'Successfully listed plans'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /plans/{planId}:
    get:
      operationId: getPlan
      description: 'Get the details of a plan'
      parameters:
        - name: planId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Successfully returned plan details'
          content:
            application/json:
              schema:
                type: object
        '400':
          description: 'Invalid request'
          content:
            application/json:
              schema:
                type: object

  /strategies:
    get:
      operationId: getStrategies
      description: 'Get all the strategies that can be used within the solver'
      responses:
        '200':
          description: 'Successfully returned strategies'
          content:
            application/json:
              schema:
                type: object

  /plans/{planId}/apply:
    post:
      operationId: applyPlan
      description: 'Apply plan to input and return the transformation'
      parameters:
        - name: planId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SolveRequest'
      responses:
        '200':
          description: 'Plan applied successfully'
          content:
            application/json:
              schema:
                $ref: 'Transformation.yaml'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object

  /selectPlans:
    post:
      operationId: selectPlans
      description: 'Select appropriate plans for given expression'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SolveRequest'
      responses:
        '200':
          description: 'Plans selected successfully'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'PlanSelection.yaml'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    Format:
      type: string
      enum: [latex, solver, json2]
      default: solver
    SolveRequest:
      type: object
      required:
        - input
        - format
      properties:
        input:
          type: string
        context:
          $ref: 'Context.yaml'
        format:
          $ref: '#/components/schemas/Format'
