title: Category
description: Various data about a category
type: object
required:
  - metadata
  - explanations
properties:
  metadata:
    description: Contains general data about the category
    type: object
    required:
      - name
      - title
    properties:
      name:
        description: The name of the category in PascalCase
        type: string
      title:
        description: A human-readable name for the category
        type: string

  methods:
    description: Maps method IDs to method specifications
    type: object
    additionalProperties:
      description: Method ID
      type: object
      required:
        - visibility
        - description
        - implementationName
      properties:
        visibility:
          description: Availability of the plan
          type: string
          enum: [ 'public', 'internal' ]
        description:
          description: Description of the plan in US English - this text will be localized
          type: string
        implementationName:
          description: Name of the Kotlin package-level identifier containing the plan implementation
          type: string
