complexity:
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 20
  LongMethod:
    excludes: ['**/test/**']
style:
  MagicNumber:
    excludes: ['**/test/**', '**/engine/expressions/Constants.kt']

