complexity:
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 20
  LongMethod:
    excludes: ['**/test/**']
style:
  DestructuringDeclarationWithTooManyEntries:
    maxDestructuringEntries: 4
  ReturnCount:
    max: 3
  MagicNumber:
    ignoreNumbers: ['-1', '0', '1', '2', '3']
    excludes: ['**/test/**', '**/engine/expressions/Constants.kt']
