complexity:
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 20
  LongMethod:
    excludes: [ '**/test/**' ]
style:
  ReturnCount:
    max: 3
  MagicNumber:
    excludes: [ '**/test/**', '**/engine/expressions/Constants.kt' ]

