openapi: 3.0.3

info:
  title: "GeoGebra Solver API"
  version: "1.0-alpha0"

paths:
  /plans:
    get:
      operationId: listPlans
      description: "List all available plan IDs"
      responses:
        "200":
          description: "Sucessfully listed plans"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /plans/{planId}:
    get:
      operationId: getPlan
      description: "Get the details of a plan"
      parameters:
        - name: planId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Successfully returned plan details"
          content:
            application/json:
              schema:
                type: object
        "400":
          description: "Invalid request"
          content:
            application/json:
              schema:
                type: object

  /plans/{planId}/apply:
    post:
      operationId: applyPlan
      description: "Apply plan to input and return the transformation"
      parameters:
        - name: planId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input
              properties:
                input:
                  type: string
      responses:
        "200":
          description: "Plan applied successfully"
          content:
            application/json:
              schema:
                $ref: 'Transformation.yaml'
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
