openapi: 3.0.3

info:
  title: "Specification for the GeoGebra Solver Engine API"
  version: "1.0"

paths:
  /applyPlan:
    post:
      description: apply a plan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - plan
                - input
              properties:
                plan:
                  type: string
                input:
                  type: string
      responses:
        "200":
          description: "Solve successful"
          content:
            application/json:
              schema:
                $ref: 'Transformation.yaml'
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
